### PR TITLE
Test how much time caching proxy saves when downloading mssql_server

### PR DESCRIPTION
**Pull request by spetrosi**

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest pending]

**Comment by spetrosi** [comment]
[citest pending]

**Comment by spetrosi** [comment]
[citest]

**Comment by nhosoi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest bad]

**Pull request closed without merging**
